version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: scheduling_db
    ports:
      - "32768:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mongodb:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    image: node:20
    container_name: backend
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: bash -c "npm run start:dev"
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - mongodb
      - redis
      - kafka
    restart: unless-stopped

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  zookeeper_data:
  kafka_data:
