[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
startCommand = "npm run deploy:start"

[env]
NODE_VERSION = "20"
NPM_CONFIG_PRODUCTION = "false" 