[build]
builder = "NIXPACKS"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npm run deploy:start"
healthcheckPath = "/health"
healthcheckTimeout = 300
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_VERSION = "20"
NPM_CONFIG_PRODUCTION = "false" 